Repository KinashServer/KinashServer, pull requests merged in 2022-01, with the labels that each got.

#88 Update server.js
  src/server.js
Labels: enhancement, status: waiting for user response

#89 Create gitignore
  public_html/.gitignore
Labels: enhancement, status: done

#90 Create index.md
  docs/index.md
Labels: documentation, enhancement, status: done
