Repository KinashServer/KinashServer, pull requests merged in 2022-02, with the labels that each got.

#122 Update app.js
  app.js
Labels: API

#125 Update app.js
  app.js
Labels: bug, status: done

#128 Massive api changes
  app.js
  changelogs.txt
  configs/config.json
  configs/default-config.json
  package.json
  public_html/login.html
Labels: API, status: almost done...

#144 Labels bug
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 1.7.x
